# Generated by Django 5.2 on 2026-02-07 11:49

import django.db.models.deletion
import horilla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_actiontype_action_type_alter_employee_dob_and_more'),
        ('horilla_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'verbose_name': 'Richiesta Documento', 'verbose_name_plural': 'Richieste Di Documento'},
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=horilla.models.upload_path, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Dipendente'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_digital_asset',
            field=models.BooleanField(default=False, verbose_name='È Un Asset Digitale'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Di Emissione'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notify_before',
            field=models.IntegerField(default=1, null=True, verbose_name='Notifica Prima'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Rifiuta Motivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=10, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='employee_id',
            field=models.ManyToManyField(to='employee.employee', verbose_name='Dipendenti'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='format',
            field=models.CharField(choices=[('any', 'Any'), ('pdf', 'PDF'), ('txt', 'TXT'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('jpg', 'JPG'), ('png', 'PNG'), ('jpeg', 'JPEG')], max_length=10, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='max_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dimensione massima (in MB)'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titolo'),
        ),
    ]
